### ISSUE TITLE
Linking with SFML fails on linux

### ISSUE THREAD

**Issue by benishor** [7thFACTOR/horus_ui#2]
Linking `custom_render_and_input fails` on linux. This is what we get:

``/usr/bin/x86_64-linux-gnu-ld: ../3rdparty/sfml/linux/lib/libsfml-window-s.a(JoystickManager.cpp.o): relocation R_X86_64_32S against symbol `_ZNSbIjSt11char_traitsIjESaIjEE4_Rep20_S_empty_rep_storageE' can not be used when making a PIE object; recompile with -fPIC``

Fix it.

**Comment by nekitu** [comment]
SFML was taken out for now. /examples/common contains the implementation for the input provider if anyone needs it.
